### ISSUE TITLE
Firefox Developer Edition download failed

### ISSUE THREAD

**Issue by AESM** [caskroom/homebrew-versions#2740]
#### Attempt & Results:
``` sh
~ :> brew cask install caskroom/versions/firefoxdeveloperedition
==> Downloading https://download.mozilla.org/?product=firefox-aurora-latestssl&os=osx&lang=en-US

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'firefoxdeveloperedition' with message: Download failed: https://download.mozilla.org/?product=firefox-aurora-latestssl&os=osx&lang=en-US
The incomplete download is cached at /Users/USERNAME/Library/Caches/Homebrew/Cask/firefoxdeveloperedition--latest.incomplete
```

``` sh
## Homebrew status
~ :> brew -v
Homebrew 1.0.7
Homebrew/homebrew-core (git revision e58d7; last commit 2016-10-10)

## Local application status
~ :> brew cask info firefoxdeveloperedition
firefoxdeveloperedition: latest
https://www.mozilla.org/firefox/developer/
Not installed
From: https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefoxdeveloperedition.rb
==> Name
Mozilla Firefox Developer Edition
==> Artifacts
FirefoxDeveloperEdition.app (app)
```

#### Additional Info:
- macOS Sierra v10.12
- Attempted in both Bash & Zsh
- iTerm2 user
- Previously, Firefox Developer Edition was successfully installed by the same means
- Results were the same when attempted with `--force` flag

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.

**Comment by vitorgalvao** [comment]
Fixed by https://github.com/caskroom/homebrew-versions/pull/2734.
